language: node_js
node_js:
  - '0.10'
  - '0.8'
script: "npm run-script travis"
before_script:
  - npm install -g bower mocha istanbul generator-angular
  - export NODE_PATH="$NVM_PATH/../node_modules"
env:
  - DEBUG="generators:*"
